### ISSUE TITLE
s3 providers

### ISSUE THREAD

**Issue by gedw99** [casbin/confita#1]
sems that https://github.com/aliyun/aliyun-oss-go-sdk is the only option ?

would be cool with ability to use any s3 provider. I think there are quite a few golang libs that can do this.

**Comment by hsluoyz** [comment]
@gedw99 that part of code is only used for putting frontend files into CDN. It's optional. BTW are you using this project?

**Comment by gedw99** [comment]
Hey @hsluoyz 

thanks for the response. I am usibg it for similar purposes

**Comment by gedw99** [comment]
Are you planning to make this more s3 agnostic ?

**Comment by hsluoyz** [comment]
@gedw99 finally it will switch to use the provider: https://casdoor.org/docs/provider/storage/storage , can you make a PR for it?

**Comment by gedw99** [comment]
@hsluoyz 

I had a look and that link refers to the following code ?

 https://github.com/casdoor/casdoor/blob/master/storage/storage.go

Which itself uses: https://github.com/casdoor/oss.

**Comment by hsluoyz** [comment]
Closed as stale.
